DROP TABLE IF EXISTS `test_record`;
CREATE TABLE `test_record` (
  `id` varchar(100) NOT NULL,
  `url` varchar(100) DEFAULT NULL,
  `FRD` text,
  `LUD` text,
  `SD` text,
  `EPCD1` text,
  `CPOM` text,
  `OPOM` text,
  `CH` text,
  `CSOM` text,
  `OSOM` text,
  `COOM` text,
  `OOOM` text,
  `BT` text,
  `OT` text,
  `BS` text,
  `DD` text,
  `ST` text,
  `SP` text,
  `SDs` text,
  `Co` text,
  `Intv` text,
  `SA` text,
  `Pub` text,
  `RS` text,
  `EE` text,
  `CD` text,
  `EPCD2` text,
  `EC` text,
  `Gend` text,
  `Age` text,
  `AHV` text,
  `Cont` text,
  `LC` text,
  `NCTN` text,
  `OSID` text,
  `HDMC` text,
  `RP` text,
  `SS` text,
  `Coll` text,
  `Inves` text,
  `IPB` text,
  `VD` text,
  PRIMARY KEY (`id`)
)